Azure Manifest tests for service availability and pipeline execution
kaizentm/kubemlops pull request #90
Opened 2020-10-06 05:15 UTC by yilun-msft

Created pipelines to monitor the service availability and pipeline execution for Azure Manifest on Kubeflow.org. The tests are two-folds. First to check service availability, i.e. KF pods are ready and healthy. Second to check a pipeline artifact could be created and executed. These sets of tests would be used to constantly monitor Azure Manifest and make sure Kubeflow could be installed on AKS and a simple set of pipeline could be executed.

2020-10-09 00:41 UTC, eedorenko requested changes

2020-10-09 00:41 UTC, eedorenko commented on .github/workflows/manifest_test.yml
> +          # Create AKS resources
That's too long for an inline script from readability perspective. Can you move it to a shell script and define all used constants (like URLs, Istio version) at the top of the script?

2020-10-09 00:41 UTC, eedorenko commented on code/tests/manifest_tests.py
> +    client = kfp.Client()
Does it work fro you? Without any parameters?

2020-10-09 00:47 UTC, yilun-msft commented on code/tests/manifest_tests.py
> +    client = kfp.Client()
Yup. It passed the tests: https://github.com/yilun-msft/kubemlops/actions?query=workflow%3AManifest_Test

2020-10-09 00:47 UTC, yilun-msft commented on .github/workflows/manifest_test.yml
> +          # Create AKS resources
Sure. Will update

2020-10-09 16:39 UTC, eedorenko commented on .github/workflows/manifest_test.yml
> +  build_images_for_manifest_test:
Why is it called "build_images_..."? What images do we build?

2020-10-14 07:18 UTC, yilun-msft commented on .github/workflows/manifest_test.yml
> +  build_images_for_manifest_test:
Changed.

2020-10-14 07:19 UTC, yilun-msft commented on .github/workflows/manifest_test.yml
> +          # Create AKS resources
Updated to use a shell script with env defined in yaml file.

2020-10-14 19:57 UTC, eedorenko approved these changes

2020-10-14 19:57 UTC, merged